/* AUTO-GENERATED by scripts/update-release-meta.mjs. Do not edit manually. */
export type ReleaseCommit = {
  commit: string
  date: string
  message: string
  current: boolean
}

export const RELEASE_META = {
  version: 'v1.5.0',
  latestCommit: '1a02144',
  lastPublished: '06 Apr 2026',
  repoLabel: 'viharnar / codex',
  repoUrl: 'https://github.com/vnar/reg-sdlc',
  authorName: 'Vihar Nar',
  authorUrl: 'https://www.linkedin.com/in/viharnar/',
} as const

export const RELEASE_COMMITS: ReleaseCommit[] = [
  {
    "commit": "1a02144",
    "date": "06 Apr 2026",
    "message": "Release v1.5.0",
    "current": true
  },
  {
    "commit": "cb2b786",
    "date": "21 Mar 2026",
    "message": "feat: add top-frame About modal with blur overlay",
    "current": false
  },
  {
    "commit": "29f3f6b",
    "date": "21 Mar 2026",
    "message": "feat: add lightweight feedback widget with silent submit flow",
    "current": false
  },
  {
    "commit": "d8082c0",
    "date": "21 Mar 2026",
    "message": "fix: enable GA4 SPA tracking with route-based pageviews",
    "current": false
  },
  {
    "commit": "1936cf4",
    "date": "21 Mar 2026",
    "message": "feat: add mobile-first LinkedIn deep link with web fallback",
    "current": false
  },
  {
    "commit": "0a6e539",
    "date": "21 Mar 2026",
    "message": "fix: improve lifecycle architecture mobile legibility",
    "current": false
  },
  {
    "commit": "beb9c50",
    "date": "21 Mar 2026",
    "message": "feat: add GA4 SPA route tracking",
    "current": false
  },
  {
    "commit": "8d88153",
    "date": "21 Mar 2026",
    "message": "chore: add GA tracking and refresh release metadata",
    "current": false
  },
  {
    "commit": "7012217",
    "date": "21 Mar 2026",
    "message": "fix mobile legibility and auto-sync release metadata",
    "current": false
  },
  {
    "commit": "4300c4b",
    "date": "21 Mar 2026",
    "message": "refine mobile polish and AI use-case readability",
    "current": false
  },
  {
    "commit": "a8d14d5",
    "date": "20 Mar 2026",
    "message": "fix: post-review site polish + AI Enablement typography",
    "current": false
  },
  {
    "commit": "69dacf6",
    "date": "20 Mar 2026",
    "message": "feat: mobile responsive styles (≤768px) and traceability/classification hooks",
    "current": false
  }
] as ReleaseCommit[]
