/* AUTO-GENERATED by scripts/update-release-meta.mjs. Do not edit manually. */
export type ReleaseCommit = {
  commit: string
  date: string
  message: string
  current: boolean
}

export const RELEASE_META = {
  version: 'v1.0.0',
  latestCommit: '7012217',
  lastPublished: '21 Mar 2026',
  repoLabel: 'viharnar / codex',
  repoUrl: 'https://github.com/vnar/reg-sdlc',
  authorName: 'Vihar Nar',
  authorUrl: 'https://www.linkedin.com/in/viharnar/',
} as const

export const RELEASE_COMMITS: ReleaseCommit[] = [
  {
    "commit": "7012217",
    "date": "21 Mar 2026",
    "message": "fix mobile legibility and auto-sync release metadata",
    "current": true
  },
  {
    "commit": "4300c4b",
    "date": "21 Mar 2026",
    "message": "refine mobile polish and AI use-case readability",
    "current": false
  },
  {
    "commit": "a8d14d5",
    "date": "20 Mar 2026",
    "message": "fix: post-review site polish + AI Enablement typography",
    "current": false
  },
  {
    "commit": "69dacf6",
    "date": "20 Mar 2026",
    "message": "feat: mobile responsive styles (≤768px) and traceability/classification hooks",
    "current": false
  },
  {
    "commit": "9bb75a2",
    "date": "20 Mar 2026",
    "message": "Apply post-review UX fixes across Codex pages.",
    "current": false
  },
  {
    "commit": "f024eff",
    "date": "20 Mar 2026",
    "message": "Add guarded UI regression gate for push and CI.",
    "current": false
  },
  {
    "commit": "9651ef5",
    "date": "20 Mar 2026",
    "message": "Rebrand portal UI copy and metadata to Codex.",
    "current": false
  },
  {
    "commit": "8f10648",
    "date": "20 Mar 2026",
    "message": "Polish Guardrails & Paved Roads visual hierarchy.",
    "current": false
  },
  {
    "commit": "10d8c49",
    "date": "20 Mar 2026",
    "message": "Add AI Enablement module and changelog UX enhancements.",
    "current": false
  },
  {
    "commit": "1962022",
    "date": "20 Mar 2026",
    "message": "Add Artifact Library navigation and tree template explorer",
    "current": false
  },
  {
    "commit": "d99f9db",
    "date": "20 Mar 2026",
    "message": "Polish framework presentation and export behavior for production demos.",
    "current": false
  },
  {
    "commit": "56ef861",
    "date": "20 Mar 2026",
    "message": "AppShell: restore left sidebar with collapsible rail and mobile drawer",
    "current": false
  }
] as ReleaseCommit[]
